[context.deploy-preview.environment]
    REACT_APP_NODE_ENV = "development"

[context.branch-deploy.environment]
    REACT_APP_NODE_ENV = "development"

[context.production.environment]
    REACT_APP_NODE_ENV = "production"

[functions]
  directory = "packages/prop-house-reward-api/functions"

[build]
  command = "yarn workspace prop-house-webapp build"
  publish = "packages/prop-house-webapp/build"